//
//  FrameSDKBridge.m
//  FrameReactNative
//
//  ObjC adapter that exposes the single-method `FrameSDK.initialize` Swift
//  module to React Native. All other JS-callable surfaces (Apple Pay,
//  attestation, Onboarding presentation) ship as their own modules.
//

#import <React/RCTBridgeModule.h>

// Auto-generated by CocoaPods from the pod's Swift sources during the pod build phase.
#if __has_include("FrameReactNative-Swift.h")
#import "FrameReactNative-Swift.h"
#elif __has_include(<FrameReactNative/FrameReactNative-Swift.h>)
#import <FrameReactNative/FrameReactNative-Swift.h>
#else
#error "FrameReactNative-Swift.h not found. The Frame React Native pod's Swift code did not generate its module header — check that pod install ran cleanly."
#endif

@interface FrameSDKModule : NSObject <RCTBridgeModule>
@end

@interface RCT_EXTERN_MODULE(FrameSDK, FrameSDKModule)

RCT_EXTERN_METHOD(initialize:(NSString *)secretKey
                  publishableKey:(NSString *)publishableKey
                  debugMode:(BOOL)debugMode
                  applePayMerchantId:(id)applePayMerchantId
                  googlePayMerchantId:(id)googlePayMerchantId
                  theme:(NSDictionary *)theme
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

@end

@implementation FrameSDK
@end

@implementation FrameSDKModule

+ (BOOL)requiresMainQueueSetup {
  return YES;
}

- (void)initialize:(NSString *)secretKey publishableKey:(NSString *)publishableKey debugMode:(BOOL)debugMode applePayMerchantId:(id)applePayMerchantId googlePayMerchantId:(id)googlePayMerchantId theme:(NSDictionary *)theme resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject {
  [[[ObjCFrameSDKBridge alloc] init] initialize:secretKey publishableKey:publishableKey debugMode:debugMode applePayMerchantId:applePayMerchantId googlePayMerchantId:googlePayMerchantId theme:theme resolver:resolve rejecter:reject];
}

@end
